### ISSUE TITLE
⭐️ in README and Dockerfile

### ISSUE THREAD

**Issue by BooBSD** [maximdanilchenko/aiochclient#10]
I'm trying to install `aiochclient==1.0.2` in `Dockerfile` and get next error:

```
Collecting aiochclient==1.0.2 (from -r /app/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ca/5c/33326e9edb67be58b96ae2f24d30c3cdbfbd8876ef422dc0922a04140edd/aiochclient-1.0.2.tar.gz (118kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8wcsrg2m/aiochclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8wcsrg2m/aiochclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-8wcsrg2m/aiochclient/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8wcsrg2m/aiochclient/setup.py", line 53, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-install-8wcsrg2m/aiochclient/setup.py", line 45, in read
        content = fp.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4787: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It seems that your ⭐️ in `README` is a problem.

**Comment by maximdanilchenko** [comment]
@BooBSD why did you close the issue? Is it alright now?

**Comment by BooBSD** [comment]
@maximdanilchenko 

I found out that next two lines have helped me.:
```
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
RUN apt-get install -y locales && locale-gen en_US.UTF-8
```

**Comment by maximdanilchenko** [comment]
@BooBSD thank you for an explanation!
