### ISSUE TITLE
sqlparse is a hard requirement but not listed as such

### ISSUE THREAD

**Issue by xhochy** [maximdanilchenko/aiochclient#21]
See the following traceback:

```
import: 'aiochclient'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/aiochclient_1582137580250/test_tmp/run_test.py", line 2, in <module>
    import aiochclient
  File "/home/conda/feedstock_root/build_artifacts/aiochclient_1582137580250/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/aiochclient/__init__.py", line 1, in <module>
    from aiochclient.client import ChClient
  File "/home/conda/feedstock_root/build_artifacts/aiochclient_1582137580250/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/aiochclient/client.py", line 10, in <module>
    from aiochclient.sql import sqlparse
  File "/home/conda/feedstock_root/build_artifacts/aiochclient_1582137580250/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.6/site-packages/aiochclient/sql.py", line 3, in <module>
    import sqlparse.keywords
ModuleNotFoundError: No module named 'sqlparse'
```

**Comment by maximdanilchenko** [comment]
https://pypi.org/project/aiochclient/1.3.1/
