### ISSUE TITLE
imposible to select data with type  'DateTime64(3)

### ISSUE THREAD

**Issue by niko83** [maximdanilchenko/aiochclient#36]
It is imposible to select data with type  'DateTime64(3)

1)
`
         CREATE TABLE IF NOT EXISTS tablename                                    
             (timestamp DateTime64(3),.........
`

2)
`SELECT timestamp  from tablename`

3)
`
Traceback (most recent call last):
  File "aiochclient/_types.pyx", line 588, in aiochclient._types.what_py_type
KeyError: 'DateTime64'
`

`  File "...../venv/lib/python3.7/site-packages/aiochclient/records.py", line 89, in <listcomp>
    what_py_converter(tp) for tp in tps.decode().strip().split("\t")
  File "aiochclient/_types.pyx", line 593, in aiochclient._types.what_py_converter
  File "aiochclient/_types.pyx", line 595, in aiochclient._types.what_py_converter
  File "aiochclient/_types.pyx", line 590, in aiochclient._types.what_py_type
aiochclient.exceptions.ChClientError: Unrecognized type name: 'DateTime64(3)'
`

**Comment by maximdanilchenko** [comment]
@niko83 thank you for the issue. It does not support DateTime64 type yet. I will add it soon.
