### ISSUE TITLE
DateTime64 Conversion Error

### ISSUE THREAD

**Issue by dnelw** [maximdanilchenko/aiochclient#49]
Hi there,

Currently running into a crash when trying to access a DateTime64 value at the precision level of nanoseconds instead of milliseconds.

I'll try to monkeypatch it on my end but to be honest I'm completely lost.

Traceback:
```
Traceback (most recent call last):
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user.name/folder/folder/__main__.py", line 48, in <module>
    entry_point()
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user.name/folder/folder/__main__.py", line 27, in entry_point
    asyncio.run(main(config))
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user.name/folder/folder/__main__.py", line 41, in main
    artifacts = await current_comparer.main()
  File "/home/user.name/folder/folder/comparers/default_comparer.py", line 40, in main
    print(list(row.values()))
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/_collections_abc.py", line 762, in __iter__
    yield self._mapping[key]
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/site-packages/aiochclient/records.py", line 46, in __getitem__
    self._decode()
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/site-packages/aiochclient/records.py", line 74, in _decode
    self._row = tuple(
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/site-packages/aiochclient/records.py", line 75, in <genexpr>
    converter(val)
  File "aiochclient/_types.pyx", line 389, in aiochclient._types.DateTime64Type.convert
  File "aiochclient/_types.pyx", line 390, in aiochclient._types.DateTime64Type.convert
  File "aiochclient/_types.pyx", line 384, in aiochclient._types.DateTime64Type._convert
  File "aiochclient/_types.pyx", line 379, in aiochclient._types.DateTime64Type._convert
  File "stringsource", line 67, in cfunc.to_py.__Pyx_CFunc_datetime____unicode___to_py.wrap
  File "aiochclient/_types.pyx", line 20, in aiochclient._types._datetime_parse_f
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/user.name/anaconda3/envs/folder/lib/python3.8/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: 132
```

Thanks so much

**Comment by dnelw** [comment]
Ahh so after some more investigation, in `datetime_parse_f` we call `dt.datetime.strptime(string, '%Y-%m-%d %H:%M:%S.%f')` and %f only supports up to microsecond accuracy, not nanoseconds.

I guess I can monkeypatch on my end to use a different converter like pandas.to_datetime()
